# Generated by Django 6.0 on 2026-09-14 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='fa-stethoscope', help_text='FontAwesome icon class name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(help_text='e.g. MBBS, MD, MS', max_length=150)),
                ('specialization', models.CharField(help_text='e.g. Cardiologist, Dermatologist', max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=5)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('clinic_name', models.CharField(default='DocPulse Care Clinic', max_length=200)),
                ('clinic_address', models.TextField(default='123 Health Ave, Medical District')),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=48)),
                ('is_verified', models.BooleanField(default=True, help_text='Doctor verification status')),
                ('available_days', models.CharField(default='Monday - Saturday', max_length=100)),
                ('working_hours', models.CharField(default='09:00 AM - 05:00 PM', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-experience_years'],
            },
        ),
    ]
